


  external_node_modules = ["express"]
  node_bundler = "esbuild"


  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"




  base = "backend"
  publish = "build"
  command = "npm run build"

  directory = "backend"

  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

